export const Deco = {
    Header: {
        // outer wrapper
        Wrapper: "surface-1 border-b border-surface-variant sticky top-0 z-50 w-full",

        // layout container
        MobileContainer: "md:hidden flex flex-col px-5 py-4 layout-container border-none",
        MobileTopBar: "flex justify-between items-center w-full",
        DesktopContainer: "hidden md:flex justify-between items-center h-20 layout-container border-none sticky-none",

        // logo
        LogoWrapper: "flex items-center",
        LogoIcon: "w-8 h-8 md:w-10 md:h-10 text-primary mr-2",
        LogoText: "text-primary font-bold font-playfair text-headline-sm lg:text-headline-md",

        // Nav
        MobileNavList: "flex flex-col gap-6 text-on-surface-variant tracking-[0.08em] mt-4 text-label-caps",
        DesktopNavList: "flex gap-8 text-on-surface-variant tracking-[0.08em] text-label-caps",
        NavLink: "hover:text-secondary cursor-pointer transition-colors duration-200",

        // profile Btn
        ProfileBtn: "w-10 h-10 rounded-full bg-surface-container-high text-primary flex items-center justify-center hover:bg-surface-variant transition-colors duration-200 cursor-pointer",
    },
    Footer: {
        Wrapper: "bg-[#edeeef] py-16 mt-16 w-full",
        Container: "layout-container flex flex-col gap-4",
        LogoText: "text-primary font-bold font-playfair text-[28px]",
        BottomRow: "flex flex-col md:flex-row justify-between items-start md:items-end gap-6 w-full",
        Copyright: "text-[12px] text-on-surface-variant",
        NavList: "flex flex-wrap items-center gap-6",
        NavLink: "text-[12px] text-on-surface-variant hover:text-primary underline cursor-pointer transition-colors"
    },
    PubHeader: {
        SignInBtn: "px-6 py-2.5 font-inter font-medium text-primary hover:text-secondary hover:bg-surface-variant transition-colors duration-300 rounded text-[14px] uppercase tracking-[0.05em] cursor-pointer",
        SignUpBtn: "px-6 py-2.5 font-inter font-semibold bg-primary text-on-primary rounded text-[14px] uppercase tracking-[0.05em] shadow-sm hover:bg-secondary hover:text-on-secondary hover:shadow-md transition-all duration-300 cursor-pointer"
    },
    PubHome: {
        HeroWrapper: "pub-hero-wrapper",
        HeroContainer: "layout-container flex flex-col items-center text-center",
        HeroTitle: "pub-hero-title text-display-lg-mobile md:text-display-lg",
        HeroSubtitle: "pub-section-subtitle text-body-lg md:text-[20px] mb-10",
        HeroCTAWrapper: "flex flex-col sm:flex-row items-center justify-center gap-4 mt-8",
        HeroPrimaryCTA: "w-full sm:w-auto px-8 py-4 bg-primary text-on-primary font-semibold rounded-full hover:bg-primary-container transition-colors uppercase tracking-[0.05em] shadow-lg shadow-primary/20",
        HeroSecondaryCTA: "w-full sm:w-auto px-8 py-4 bg-transparent border-2 border-secondary text-primary font-semibold rounded-full hover:bg-surface-variant transition-colors uppercase tracking-[0.05em]",

        FeaturesWrapper: "surface-1 pub-section-wrapper",
        FeaturesContainer: "layout-container",
        SectionHeader: "text-center mb-16",
        SectionTitle: "pub-section-title text-headline-md",
        SectionSubtitle: "pub-section-subtitle text-body-lg",
        FeaturesGrid: "pub-features-grid",
        FeatureCard: "pub-feature-card",
        FeatureIconWrapper: "pub-feature-icon",
        FeatureTitle: "text-headline-sm text-primary mb-3",
        FeatureDesc: "text-body-md text-on-surface-variant",

        TrustWrapper: "bg-primary text-on-primary pub-section-wrapper !border-none",
        TrustContainer: "layout-container pub-trust-container",
        TrustContent: "flex-1 text-center md:text-left",
        TrustTitle: "pub-hero-title text-display-lg-mobile md:text-display-lg !text-on-primary !mb-6 !leading-tight",
        TrustDesc: "text-inverse-primary text-body-lg mb-10 max-w-xl opacity-90 leading-relaxed",
        TrustStatsContainer: "pub-trust-stats",
        TrustStat: "flex flex-col",
        TrustStatValue: "pub-stat-value",
        TrustStatLabel: "text-label-caps text-inverse-primary mt-2",

        FinalCTAWrapper: "bg-background pub-section-wrapper text-center",
        FinalCTATitle: "pub-section-title text-headline-md max-w-2xl mx-auto mb-6",
        SecondaryCTA: "btn-outline-gold mt-4"
    },
    AuthHome: {
        Wrapper: "flex flex-col min-h-screen bg-background text-on-background font-jakarta pb-20",
        Main: "flex-1 flex flex-col items-center pt-12 md:pt-20 px-5 layout-container w-full",

        // Hero - Compact Dashboard Strip
        HeroWrapper: "flex flex-col items-center justify-center w-full max-w-4xl mb-12 text-center",
        Greeting: "text-display-lg-mobile md:text-display-lg text-primary mb-4 leading-tight",
        LocationBadge: "inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-surface-container text-on-surface-variant text-label-md cursor-pointer hover:bg-surface-variant transition-colors border border-surface-variant shadow-sm mt-2",
        LocationIcon: "w-5 h-5 text-[#D4AF37]",
        LocationEditIcon: "w-4 h-4 text-outline opacity-60",
        StatsContainer: "flex flex-wrap justify-center gap-6 mt-8",
        StatWidget: "flex flex-col items-center px-8 py-6 bg-surface-container-lowest rounded-2xl border border-surface-variant shadow-sm",
        StatValue: "text-headline-md text-primary font-playfair",
        StatLabel: "text-label-caps text-on-surface-variant mt-2",

        // Pincode Location Input (kept for reference, currently unused)
        PincodeDropdown: "absolute top-full left-1/2 -translate-x-1/2 mt-3 bg-surface-container-lowest rounded-xl border border-surface-variant shadow-lg p-4 z-50 flex items-center gap-2 min-w-[280px]",
        PincodeInput: "flex-1 bg-transparent border border-surface-variant rounded-lg px-3 py-2 text-body-md text-on-surface placeholder:text-outline outline-none focus:border-primary transition-colors",
        PincodeBtn: "px-4 py-2 bg-primary text-on-primary font-inter font-semibold text-[12px] uppercase tracking-[0.05em] rounded-lg hover:bg-primary-container transition-colors whitespace-nowrap",

        // Tools Grid — 3 columns
        ToolsGrid: "grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-5xl mb-16",
        ToolCard: "flex flex-col p-8 bg-surface-container-lowest rounded-3xl border border-surface-variant shadow-sm hover:shadow-md hover:border-[#D4AF37]/40 transition-all cursor-pointer group",
        ToolHeader: "flex items-center gap-4 mb-4",
        ToolIconWrapper: "w-14 h-14 rounded-2xl bg-primary-fixed flex items-center justify-center text-primary shadow-sm group-hover:bg-[#D4AF37]/20 transition-colors",
        ToolIcon: "w-7 h-7",
        ToolTitle: "text-headline-sm text-primary",
        ToolDesc: "text-body-md text-on-surface-variant opacity-90 leading-relaxed flex-1",
        ToolArrow: "self-end mt-4 w-10 h-10 rounded-full bg-surface-container flex items-center justify-center text-primary group-hover:bg-[#D4AF37] group-hover:text-on-primary transition-all",
        ToolArrowIcon: "w-5 h-5",

        // Did You Know — Health Tips
        TipsSection: "w-full max-w-5xl mb-16",
        TipsHeading: "text-headline-sm text-primary mb-6 flex items-center gap-2",
        TipsHeadingIconBox: "w-10 h-10 rounded-xl bg-primary-fixed flex items-center justify-center",
        TipsHeadingIcon: "w-5 h-5 text-[#D4AF37]",
        TipsFeaturedCard: "authhome-tip-featured",
        TipsFeaturedLayout: "flex items-start gap-5",
        TipsFeaturedIconBox: "w-14 h-14 rounded-2xl bg-primary-fixed flex items-center justify-center shrink-0 group-hover:bg-[#D4AF37]/20 transition-colors",
        TipsFeaturedEmoji: "text-2xl",
        TipsFeaturedContent: "flex-1",
        TipsFeaturedCategory: "text-label-caps text-[#D4AF37] mb-2 inline-block",
        TipsFeaturedText: "text-body-lg md:text-headline-xs text-on-surface-variant leading-relaxed",
        TipsArrowLeft: "authhome-tip-arrow authhome-tip-arrow--left",
        TipsArrowRight: "authhome-tip-arrow authhome-tip-arrow--right",
        TipsDotsRow: "flex justify-center gap-2 mt-6",
        TipsDotActive: "authhome-tip-dot authhome-tip-dot--active",
        TipsDotInactive: "authhome-tip-dot authhome-tip-dot--inactive",
        TipsMiniGrid: "grid grid-cols-2 sm:grid-cols-3 gap-3",
        TipsMiniCard: "authhome-tip-mini",
        TipsMiniIconBox: "w-10 h-10 rounded-xl bg-primary-fixed flex items-center justify-center shrink-0 group-hover:bg-[#D4AF37]/20 transition-colors",
        TipsMiniEmoji: "text-lg",
        TipsMiniLabel: "text-label-caps text-on-surface-variant",

        // How It Works — 3 Steps
        HiwSection: "w-full max-w-5xl mb-16",
        HiwHeading: "text-headline-sm text-primary mb-8 text-center",
        HiwGrid: "grid grid-cols-1 md:grid-cols-3 gap-6 relative",
        HiwCard: "authhome-hiw-card",
        HiwStepNumber: "absolute -top-3 -right-2 text-[48px] font-playfair font-bold text-primary/[0.07] select-none leading-none",
        HiwIconBox: "w-16 h-16 rounded-2xl bg-primary-fixed flex items-center justify-center text-primary mb-5 group-hover:bg-[#D4AF37]/20 transition-colors",
        HiwIcon: "w-8 h-8",
        HiwTitle: "text-headline-sm text-primary mb-2",
        HiwDesc: "text-body-md text-on-surface-variant opacity-90 leading-relaxed",
        HiwConnector: "hidden md:block absolute top-1/2 -right-4 -translate-y-1/2 z-10 text-[#D4AF37]",
        HiwConnectorIcon: "w-6 h-6",
        HiwCtaRow: "flex justify-center mt-8",
        HiwCtaBtn: "authhome-hiw-cta",

        // Kept for other pages that reuse these
        DropdownWrapper: "absolute top-full left-0 right-0 mt-2 bg-surface-container-lowest rounded-lg border border-surface-variant shadow-lg z-50 overflow-hidden medi-dropdown-enter",
        DropzoneArea: "flex-1 flex flex-col items-center justify-center border-2 border-dashed border-primary/30 rounded-2xl p-8 bg-surface-container-lowest hover:bg-primary-fixed/20 transition-colors cursor-pointer min-h-[160px]",
        DropzoneIcon: "w-10 h-10 text-primary/40 mb-3",
        DropzoneText: "text-body-md text-primary font-medium",
        DropzoneSubtext: "text-body-sm text-on-surface-variant mt-1",
        RxInputWrapper: "flex flex-col sm:flex-row items-center gap-3 w-full",
        RxInputBox: "flex-1 flex items-center bg-surface-container-lowest rounded-xl p-1.5 border border-surface-variant focus-within:border-primary/50 focus-within:ring-2 focus-within:ring-primary/10 transition-all w-full shadow-sm",
        RxSearchIcon: "w-5 h-5 text-outline ml-3",
        RxInput: "w-full bg-transparent border-none outline-none px-3 py-2.5 text-body-lg text-on-surface placeholder:text-outline focus:ring-0",
        RxButton: "w-full sm:w-auto px-6 py-3.5 bg-primary text-on-primary font-semibold rounded-xl hover:bg-primary-container transition-colors text-[14px] uppercase tracking-[0.05em] shadow-sm whitespace-nowrap",
    },
    MedicineInfo: {
        WarningBox: "medi-warning-box",
        SearchContainer: "medi-search-container",
        SuggestionsWrapper: "medi-suggestions-wrapper",
        SuggestionItem: "medi-suggestion-item text-body-md",
        ResultCard: "w-full max-w-2xl mt-8 flex flex-col p-8 bg-surface-container-lowest rounded-3xl border border-surface-variant shadow-sm hover:shadow-md hover:border-[#D4AF37]/40 transition-all cursor-pointer group",
        ResultError: "text-center p-6 text-on-surface-variant font-medium",
        ResultTitle: "text-headline-sm text-primary",
        ResultContent: "mt-6 flex flex-col gap-6",
        ResultGrid: "grid grid-cols-1 md:grid-cols-2 gap-6",
        ResultHeading: "text-label-caps text-on-secondary-container uppercase font-semibold text-xs tracking-wider mb-1 block",
        ResultText: "text-body-md text-on-surface mt-1",
        ResultDivider: "h-px w-full bg-surface-variant/60"
    },
    AiChat: {
        HeaderContainer: "aichat-header-container",
        Title: "aichat-title text-display-lg-mobile md:text-display-lg",
        Subtitle: "aichat-subtitle text-body-lg",
        Disclaimer: "aichat-disclaimer text-body-sm",
        Card: "aichat-card",
        ImageSection: "aichat-image-section",
        ImagePreview: "aichat-image-preview",
        ImagePlaceholder: "aichat-image-placeholder",
        ButtonRow: "aichat-button-row",
        PrimaryButton: "aichat-primary-btn",
        SecondaryButton: "aichat-secondary-btn",
        InputSection: "aichat-input-section",
        TextArea: "aichat-textarea text-body-lg",
        SubmitButton: "aichat-submit-btn",
        ResponseCard: "aichat-response-card",
        ResponseTitle: "aichat-response-title text-headline-sm"
    },
    About: {
        Wrapper: "bg-surface-container-lowest min-h-screen flex flex-col font-jakarta pb-24",
        HeroSection: "w-full pt-24 pb-16 border-b border-surface-variant bg-surface text-center",
        HeroTitle: "text-display-lg text-primary font-playfair mb-4",
        ContentContainer: "layout-container max-w-3xl mx-auto pt-16 flex flex-col gap-8",
        Paragraph: "text-body-lg text-on-surface-variant leading-relaxed text-center"
    },
    Contact: {
        Wrapper: "bg-surface-container-lowest min-h-screen flex flex-col font-jakarta pb-24",
        HeaderSection: "w-full pt-24 pb-16 border-b border-surface-variant bg-surface text-center",
        HeaderTitle: "text-display-lg text-primary font-playfair mb-4",
        HeaderSubtitle: "text-body-lg text-[#D4AF37] font-medium tracking-wide uppercase",
        LinksContainer: "layout-container max-w-2xl mx-auto pt-16 flex flex-col gap-6 items-center",
        LinkCard: "w-full max-w-md bg-surface-container-lowest border border-surface-variant rounded-xl p-6 flex items-center justify-center gap-4 hover:border-[#D4AF37] hover:shadow-md transition-all cursor-pointer group",
        Icon: "w-6 h-6 text-primary group-hover:text-[#D4AF37] transition-colors",
        LinkText: "text-body-lg text-primary font-medium"
    },
    Profile: {
        Wrapper: "bg-background min-h-screen flex flex-col font-jakarta pb-24",
        HeaderSection: "w-full pt-16 pb-8 layout-container max-w-6xl mx-auto flex flex-col sm:flex-row justify-between sm:items-center items-start gap-4 border-b border-surface-variant/80",
        HeaderLeft: "flex flex-col gap-1",
        HeaderTitle: "text-display-lg text-primary font-playfair text-left",
        HeaderSubtitle: "text-body-lg text-on-surface-variant opacity-80 text-left mt-1",
        LogoutBtn: "px-5 py-2.5 bg-transparent border border-error text-error font-inter font-semibold text-[12px] uppercase tracking-[0.05em] rounded hover:bg-error-container hover:text-on-error hover:border-error transition-all duration-300 cursor-pointer",
        LoadingWrapper: "flex h-screen w-full items-center justify-center bg-background",
        LoadingText: "text-primary font-inter font-semibold tracking-[0.08em] uppercase",
        ErrorWrapper: "flex h-screen w-full flex-col items-center justify-center gap-4 bg-background px-6 text-center",
        ErrorTitle: "font-playfair text-[32px] text-primary font-bold",
        ErrorDesc: "max-w-md font-jakarta text-body-md text-on-surface-variant",
        MainContainer: "layout-container max-w-6xl mx-auto pt-10 relative z-10",
        ProfileGrid: "grid grid-cols-1 md:grid-cols-12 gap-8",
        InfoCard: "md:col-span-4 bg-surface-container-lowest border border-surface-variant rounded-2xl p-8 shadow-sm flex flex-col items-center text-center",
        AvatarWrapper: "w-32 h-32 rounded-full border-4 border-surface-container-lowest bg-surface-container-high flex items-center justify-center text-primary shadow-sm mb-4",
        AvatarIcon: "w-16 h-16 opacity-50",
        UserName: "text-headline-sm text-primary font-playfair mb-1",
        UserEmail: "text-body-sm text-outline mb-6",
        Badge: "inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary-fixed text-primary text-label-caps border border-primary/10 mb-6",
        InfoList: "w-full flex flex-col gap-4 text-left border-t border-surface-variant pt-6",
        InfoRow: "flex justify-between items-center",
        InfoLabel: "text-label-caps text-outline",
        InfoValue: "text-body-md text-on-surface-variant font-medium",
        StatsContainer: "md:col-span-8 flex flex-col gap-8",
        StatsGrid: "grid grid-cols-1 sm:grid-cols-3 gap-6",
        StatCard: "bg-surface-container-lowest border border-surface-variant rounded-2xl p-6 shadow-sm hover:border-[#D4AF37] transition-all group",
        StatHeader: "flex items-center gap-3 mb-4",
        StatIconWrapper: "w-12 h-12 rounded-full bg-primary-fixed flex items-center justify-center text-primary group-hover:bg-[#D4AF37] transition-colors",
        StatIcon: "w-6 h-6",
        StatTitle: "text-label-caps text-on-surface-variant",
        StatValue: "text-display-lg-mobile text-primary font-playfair",
        StatSubtext: "text-body-sm text-outline mt-1",
        ActivityCard: "bg-surface-container-lowest border border-surface-variant rounded-2xl p-8 shadow-sm",
        ActivityHeader: "text-headline-sm text-primary font-playfair mb-6",
        ActivityList: "flex flex-col gap-0",
        ActivityItem: "flex items-start gap-4 py-4 border-b border-surface-variant last:border-0",
        ActivityDot: "w-3 h-3 rounded-full bg-[#D4AF37] mt-1.5 shrink-0",
        ActivityContent: "flex flex-col",
        ActivityTitle: "text-body-md text-on-surface-variant font-medium",
        ActivityDate: "text-body-sm text-outline mt-1",
        ActivityEmpty: "text-body-md text-on-surface-variant/60 text-center py-6"
    },
    SearchPage: {
        Card: "srch-card",
        Field: "srch-field",
        Label: "srch-label",
        InputBox: "srch-input-box",
        Input: "srch-input",
        Dropdown: "srch-dropdown",
        DropdownItem: "srch-dropdown-item",
        SubmitBtn: "srch-submit",
        ResultsCard: "srch-results",
        Price: "srch-price",
        CheckIcon: "srch-check-icon",
        Hint: "srch-hint",
        TabContainer: "srch-tab-container",
        TabButton: "srch-tab-btn",
        TabButtonActiveStandard: "srch-tab-btn srch-tab-btn--standard-active",
        TabButtonActivePremium: "srch-tab-btn srch-tab-btn--premium-active",
        CurrencySymbol: "srch-currency-symbol",
        ErrorMsg: "srch-error-msg",
        ResultsTitle: "srch-results-title",
        ResultsDesc: "srch-results-desc"
    },
    QueuePage: {
        Card: "queue-card",
        PositionBadge: "queue-position-badge",
        PositionNumber: "queue-position-number",
        PositionLabel: "queue-position-label",
        ProgressTrack: "queue-progress-track",
        ProgressFill: "queue-progress-fill",
        StatusText: "queue-status-text",
        StepList: "queue-step-list",
        StepItem: "queue-step-item",
        StepDot: "queue-step-dot",
        StepDotActive: "queue-step-dot queue-step-dot--active",
        StepDotDone: "queue-step-dot queue-step-dot--done",
        StepLabel: "queue-step-label",
        InfoRow: "queue-info-row",
        InfoLabel: "text-label-caps text-outline",
        InfoValue: "text-body-md text-on-surface-variant font-medium",
        EtaBox: "queue-eta-box",
        EtaValue: "queue-eta-value",
        EtaLabel: "queue-eta-label",
    },
    SignInPage: {
        Wrapper: "flex flex-col min-h-screen bg-background items-center justify-center p-6 font-jakarta relative",
        Card: "w-full max-w-[480px] bg-surface-container-lowest rounded-lg shadow-xl shadow-primary/5 border border-surface-variant p-10 flex flex-col gap-8 relative overflow-hidden",
        TopAccent: "absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary to-[#D4AF37]",
        HeaderContainer: "text-center flex flex-col items-center",
        Title: "text-display-lg-mobile text-primary font-playfair font-bold mb-2 leading-tight",
        Subtitle: "text-body-md text-on-surface-variant",
        Field: "flex flex-col gap-2 relative",
        Label: "text-on-surface-variant font-inter text-[12px] font-bold tracking-[0.08em] uppercase",
        InputBox: "w-full bg-surface-container-lowest rounded border border-surface-variant flex items-center px-4 py-3.5 transition-all focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/10",
        Input: "w-full bg-transparent border-none outline-none text-on-surface font-jakarta text-[16px] placeholder:text-outline",
        SubmitBtn: "w-full py-4 bg-primary text-on-primary font-inter font-medium text-[14px] uppercase tracking-[0.05em] rounded hover:bg-primary-container transition-all shadow-md",
        Divider: "flex items-center text-outline my-2 text-[14px] font-jakarta before:flex-1 before:border-t before:border-surface-variant before:mr-4 after:flex-1 after:border-t after:border-surface-variant after:ml-4",
        SocialContainer: "flex justify-center gap-6",
        SocialBtn: "w-14 h-14 rounded-full border border-surface-variant bg-surface-container-lowest flex items-center justify-center text-on-surface-variant hover:text-primary hover:border-[#D4AF37] hover:bg-surface-container transition-all shadow-sm",
        FooterContainer: "mt-2 text-center",
        FooterText: "text-[16px] text-on-surface-variant",
        FooterLink: "text-[16px] font-semibold text-primary hover:text-[#D4AF37] transition-colors"
    }
};